LEARNING_RATE: 0.00001
REPLAY_BUFFER_SIZE: 10000
ALPHA: 0.5
BETA_START: 0.4
BETA_INCREMENT_PER_SAMPLING: 0.00001
LEARN_EVERY_N_STEPS: 4
MINIBATCH_SIZE: 128
DISCOUNT_FACTOR: 0.99
UPDATE_RATE: 0.005
NUMBER_EPISODES: 0 # 0 = loop until keyboardInterrupt
MAXIMUM_NUMBER_TIMESTEPS_PER_EPISODE: 100
EPSILON_STARTING_VALUE: 1
EPSILON_ENDING_VALUE: 0
EPSILON_DECAY_VALUE: 0.999