LEARNING_RATE: 0.0001
REPLAY_BUFFER_SIZE: 10000
LEARN_EVERY_N_STEPS: 4
MINIBATCH_SIZE: 100
DISCOUNT_FACTOR: 0.99
NUMBER_EPISODES: 0 # 0 = loop until keyboardInterrupt
MAXIMUM_NUMBER_TIMESTEPS_PER_EPISODE: 200
EPSILON_STARTING_VALUE: 1
EPSILON_ENDING_VALUE: 0.05
EPSILON_DECAY_VALUE: 0.995